<a href="https://colab.research.google.com/github/gurukjy/keras/blob/master/01_PyTorch_Basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# PyTorch 101

- PyTorch tutorial website 참고(https://tutorials.pytorch.kr/beginner/deep_learning_60min_blitz.html)
- PyTorch is multidimensional arrays, tensors and an extensive library of operations on them

In [2]:
# torch가 설치되어 있지 않다면
# https://pytorch.org 에서 환경에 맞는 command로 설치하거나
# !pip install torch 또는 !pip3 install torch (Python3 환경임을 명시)

import torch

## 1. Tensor

- PyTorch의 기본 단위이며 Numpy의 배열과 유사하다

### 텐서 만들기

In [3]:
# Create a torch.Tensor object with the given data.  It is a 1D vector
V_data = [1., 2., 3.]
V = torch.Tensor(V_data)
print(V)

# Creates a matrix
M_data = [[1., 2., 3.], [4., 5., 6]]
M = torch.Tensor(M_data)
print(M)

# Create a 3D tensor of size 2x2x2.
T_data = [[[1.,2.], [3.,4.]],
          [[5.,6.], [7.,8.]]]
T = torch.Tensor(T_data)
print(T)

tensor([1., 2., 3.])
tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]]])


In [4]:
# torch.ones: create a tensor filled with 1.0
a = torch.ones(3)
print(a)

b = torch.ones(2, 3)
print(b)

tensor([1., 1., 1.])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [5]:
# torch.zeros: create a tensor filled with 0.0
c = torch.zeros(4)
print(c)

d = torch.zeros(5, 2, 3)
print(d)

tensor([0., 0., 0., 0.])
tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])


In [11]:
# 초기화하면서 현재 메모리에 존재하는 값
x = torch.empty(5, 3)
print(x)

x = torch.rand(5, 3)
print(x)

tensor([[-2.0151e+24,  3.0845e-41,  2.3694e-38],
        [ 7.6892e-06,  3.6893e+19,  1.8604e+00],
        [ 1.8487e+00,  1.8672e+00,  1.8555e+00],
        [ 5.2789e-01,  2.8083e-01,  4.5886e-01],
        [ 9.3774e-01,  6.9075e-01,  9.0900e-01]])
tensor([[6.2074e-01, 1.9566e-01, 8.2028e-04],
        [6.8786e-01, 7.0338e-01, 7.9815e-01],
        [9.6325e-02, 8.3201e-01, 4.2942e-01],
        [4.1835e-01, 2.1993e-01, 3.9834e-01],
        [3.7861e-01, 3.5190e-02, 6.7799e-01]])


In [12]:
# torch.rand: Returns a tensor filled with random numbers from a uniform distribution on the interval [0, 1)
rand_points = torch.rand(4, dtype=torch.double)
print(rand_points)

rand_points_2 = torch.rand(2, 3, dtype=torch.float)
print(rand_points_2)

# torch.long

tensor([0.2554, 0.5459, 0.7655, 0.5240], dtype=torch.float64)
tensor([[0.7643, 0.0831, 0.4229],
        [0.0875, 0.0352, 0.8014]])


In [13]:
# torch.randn: Returns a tensor filled with random numbers
# Use normal distribution with mean 0 and variance 1
# also called the standard normal distribution

randn_points = torch.randn(3, 3)
print(randn_points)

tensor([[ 0.3319,  1.0240, -0.6789],
        [-1.9956,  0.3716,  1.7547],
        [-0.6850,  0.8924, -1.0870]])


In [14]:
# Compute size of matrix
print(randn_points.size())

torch.Size([3, 3])


- 실습

1. 5 by 4 의 empty tensor를 생성한다
2. 3 x 3 의 one matrix를 생성한다
3. 2 x 2 의 zero matrix를 생성한다
4. 3 x 5의 rand 행렬을 생성한다


In [17]:
print(torch.empty(5,4))
print(torch.ones(3,3))
print(torch.zeros(2,2))
print(torch.rand(3,5))

tensor([[-2.6045e+24,  3.0845e-41,  7.0065e-44,  6.8664e-44],
        [ 6.3058e-44,  6.7262e-44,  7.1466e-44,  6.3058e-44],
        [ 7.0065e-44,  7.2868e-44,  1.1771e-43,  6.7262e-44],
        [ 6.8664e-44,  8.1275e-44,  6.7262e-44,  7.9874e-44],
        [ 8.1275e-44,  6.7262e-44,  7.7071e-44,  6.4460e-44]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0.],
        [0., 0.]])
tensor([[0.9551, 0.2190, 0.0300, 0.5759, 0.2755],
        [0.8098, 0.6632, 0.1237, 0.7171, 0.1678],
        [0.5125, 0.7470, 0.3219, 0.8345, 0.4490]])


### 텐서 인덱스

In [18]:
temp = torch.Tensor([0, 1, 2, 3, 4, 5, 6, 7])

print(temp[:]) # tensor element 전체
print(temp[1:4]) # index 1과 4 사이의 원소들 출력
print(temp[1:]) # index 1부터의 원소들 출력
print(temp[:4]) # index 4까지의 원소들 출력
print(temp[-1]) # 뒤에서 첫번째 원소 출력
print(temp[:-1]) # index -1 = 뒤에서부터 index 1에 해당하는 원소까지만 출력
print(temp[1:6:2]) # index 1과 6 사이의 원소 출력, 이때 2개 단위로 건너뛰면서

tensor([0., 1., 2., 3., 4., 5., 6., 7.])
tensor([1., 2., 3.])
tensor([1., 2., 3., 4., 5., 6., 7.])
tensor([0., 1., 2., 3.])
tensor(7.)
tensor([0., 1., 2., 3., 4., 5., 6.])
tensor([1., 3., 5.])


In [19]:
temp2 = torch.Tensor([[1, 2, 3], [4, 5, 6]])

print(temp2)
print(temp2[1:])
print(temp2[1:, 1:])
print(temp2[1:, 0])

tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[4., 5., 6.]])
tensor([[5., 6.]])
tensor([4.])


- 실습

1. 7 x 10 의 ones matrix를 생성한다
2. indexing을 활용해서 위에서 만든 matrix를 3 x 3 으로 바꾼다

In [28]:
y = torch.ones(7,10)
print(y)
y[4:,7:]

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])


tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

### 텐서의 크기와 텐서 변환하기(reshape)

In [29]:
# shape: Returns the size of the tensor
a = torch.Tensor([[1, 2, 3], [4, 5, 6]])

print(a)
print(a.shape)
#reshape
#view

tensor([[1., 2., 3.],
        [4., 5., 6.]])
torch.Size([2, 3])


In [ ]:
# size()
print(a.size())

In [30]:
# Reshape: Returns a tensor with the same data and number of elements as the original tensor but with the specified shape. 
a_reshape = a.reshape(3, 2)
print(a_reshape)
print(a_reshape.shape)

a_reshape_2 = a.reshape(-1, 2) # the size -1 is inferred from other dimensions
print(a_reshape_2)
print(a_reshape_2.shape)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
torch.Size([3, 2])
tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
torch.Size([3, 2])


In [31]:
# if shape is not compatible with the current shape:
a_no_reshape = a.reshape(4, 2)

RuntimeError: ignored

In [32]:
# View: Returns a new tensor with the same data as the original tensor but of a different shape.
# reshape과 거의 비슷하게 사용

x = torch.randn(4, 4)
print(x.size())

y = x.view(16)
print(y.size())

z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(z.size())

torch.Size([4, 4])
torch.Size([16])
torch.Size([2, 8])


In [34]:
y


tensor([-1.0352, -0.8172, -0.6267, -0.4811,  0.6841, -0.7988, -1.6286, -0.6555,
        -0.9374, -0.7495, -0.4178, -2.1756, -0.4551,  0.9056, -0.6101, -0.1510])

- 실습

1. 8x8 랜덤 행렬 생성한다
2. 크기를 바꿔주는 view를 사용하여 8x8를 64로 변환한다
3. -1을 사용하여 원래 크기 8x8 을 4x4x4로 변환한다

In [40]:
print(torch.rand(8,8))
print(torch.rand(8,8).view(64))
print(torch.rand(8,8).view(-1,4,4))

tensor([[0.3605, 0.0982, 0.3184, 0.3065, 0.0135, 0.6922, 0.5099, 0.5188],
        [0.2182, 0.1823, 0.8795, 0.4962, 0.7982, 0.5057, 0.9446, 0.6584],
        [0.6741, 0.0248, 0.9763, 0.5461, 0.1244, 0.8074, 0.6853, 0.7214],
        [0.5960, 0.7095, 0.5988, 0.4389, 0.8030, 0.4449, 0.7446, 0.9876],
        [0.0308, 0.6984, 0.8827, 0.0765, 0.4911, 0.2391, 0.2185, 0.4477],
        [0.4360, 0.6366, 0.2710, 0.7434, 0.7107, 0.4309, 0.5087, 0.7227],
        [0.4059, 0.0962, 0.2785, 0.8930, 0.7809, 0.4400, 0.8960, 0.4478],
        [0.3706, 0.0059, 0.8924, 0.6790, 0.0997, 0.6342, 0.5468, 0.8945]])
tensor([0.9695, 0.9731, 0.9885, 0.8523, 0.2723, 0.3540, 0.7918, 0.2609, 0.2607,
        0.9476, 0.3425, 0.8909, 0.3056, 0.6817, 0.4011, 0.8824, 0.1667, 0.4254,
        0.6708, 0.5225, 0.7429, 0.3364, 0.0550, 0.2504, 0.8467, 0.7606, 0.1532,
        0.3708, 0.3169, 0.3839, 0.0724, 0.5308, 0.6986, 0.5455, 0.4926, 0.1047,
        0.5703, 0.0825, 0.9644, 0.0111, 0.5339, 0.8681, 0.9561, 0.5093, 0.3399,
       

### 텐서 연산

In [41]:
x = torch.ones(1, 2)
print(x)
y = torch.ones(5, 3)
print(y)

tensor([[1., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [42]:
print(x+y)

RuntimeError: ignored

In [43]:
y = torch.ones(5, 2)
print(y)

# 1.
print(x+y)
# 2. 
print(torch.add(x, y))
# 3.
result = torch.empty(5, 2)
torch.add(x, y, out=result)
print(result)
# 4. inplace
print(y.add_(x))

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])
tensor([[2., 2.],
        [2., 2.],
        [2., 2.],
        [2., 2.],
        [2., 2.]])
tensor([[2., 2.],
        [2., 2.],
        [2., 2.],
        [2., 2.],
        [2., 2.]])
tensor([[2., 2.],
        [2., 2.],
        [2., 2.],
        [2., 2.],
        [2., 2.]])
tensor([[2., 2.],
        [2., 2.],
        [2., 2.],
        [2., 2.],
        [2., 2.]])


### 텐서를 numpy로 변환하기

In [ ]:
# tensor to numpy array

points = torch.ones(3, 4)
points_np = points.numpy()

print(points_np)

In [ ]:
# numpy arrray to tensor
points = torch.from_numpy(points_np)

print(points)

#### List, Numpy 배열을 텐서로 만들기

In [45]:
import numpy as np

In [46]:
l = [13,4] # 리스트 생성
r = np.array([4,56,7]) # 넘파이 배열 생성

In [47]:
torch.tensor(l) # 리스트를 텐서로 쉽게 변환할 수 있다.

tensor([13,  4])

In [48]:
torch.tensor(r) # 넘파이 배열을 텐서로 쉽게 변환할 수 있다.

tensor([ 4, 56,  7])

## Backpropagation

- PyTorch는 역전파(backpropagation)를 위한 자동미분 제공

In [49]:
# Dataloader , Dataset
# kaggle iris daaset , boston housing ->pytorch simple neural networks

In [50]:
# requires_grad=True는 해당 텐서(x)를 기준으로 모든 연산을 추적하는 옵션이다
# 즉, x에 대해서 미분가능
x = torch.ones(2,2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [51]:
# y는 x에 대한 식
y = x + 1

# z는 y에 대한 식
z = 2*y**2

# res는 z에 대한 식이다
res = z.mean()

# x에 대해 미분가능
print("y: ", y)
print("z: ", z)
print("Result: ", res)

y:  tensor([[2., 2.],
        [2., 2.]], grad_fn=<AddBackward0>)
z:  tensor([[8., 8.],
        [8., 8.]], grad_fn=<MulBackward0>)
Result:  tensor(8., grad_fn=<MeanBackward0>)


In [52]:
# res를 기준으로 역전파를 한다
# ex. loss.backward()

# res = (z_1 + .. +z_4)/4
# z_i = 2(y_i)**2
# z_i = 2(x_i+1)**2
# d(res)/dx_i = x_i + 1

res.backward()

In [53]:
print(x)
print(x.grad)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
tensor([[2., 2.],
        [2., 2.]])
