<a href="https://colab.research.google.com/github/gurukjy/keras/blob/master/01_PyTorch_Basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# PyTorch 101

- PyTorch tutorial website 참고(https://tutorials.pytorch.kr/beginner/deep_learning_60min_blitz.html)
- PyTorch is multidimensional arrays, tensors and an extensive library of operations on them

In [2]:
# torch가 설치되어 있지 않다면
# https://pytorch.org 에서 환경에 맞는 command로 설치하거나
# !pip install torch 또는 !pip3 install torch (Python3 환경임을 명시)

import torch

## 1. Tensor

- PyTorch의 기본 단위이며 Numpy의 배열과 유사하다

### 텐서 만들기

In [3]:
# Create a torch.Tensor object with the given data.  It is a 1D vector
V_data = [1., 2., 3.]
V = torch.Tensor(V_data)
print(V)

# Creates a matrix
M_data = [[1., 2., 3.], [4., 5., 6]]
M = torch.Tensor(M_data)
print(M)

# Create a 3D tensor of size 2x2x2.
T_data = [[[1.,2.], [3.,4.]],
          [[5.,6.], [7.,8.]]]
T = torch.Tensor(T_data)
print(T)

tensor([1., 2., 3.])
tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]]])


In [4]:
# torch.ones: create a tensor filled with 1.0
a = torch.ones(3)
print(a)

b = torch.ones(2, 3)
print(b)

tensor([1., 1., 1.])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [5]:
# torch.zeros: create a tensor filled with 0.0
c = torch.zeros(4)
print(c)

d = torch.zeros(5, 2, 3)
print(d)

tensor([0., 0., 0., 0.])
tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])


In [ ]:
# 초기화하면서 현재 메모리에 존재하는 값
x = torch.empty(5, 3)
print(x)

x = torch.rand(5, 3)
print(x)

In [ ]:
# torch.rand: Returns a tensor filled with random numbers from a uniform distribution on the interval [0, 1)
rand_points = torch.rand(4, dtype=torch.double)
print(rand_points)

rand_points_2 = torch.rand(2, 3, dtype=torch.float)
print(rand_points_2)

In [ ]:
# torch.randn: Returns a tensor filled with random numbers
# Use normal distribution with mean 0 and variance 1
# also called the standard normal distribution

randn_points = torch.randn(3, 3)
print(randn_points)

In [ ]:
# Compute size of matrix
print(randn_points.size())

- 실습

1. 5 by 4 의 empty tensor를 생성한다
2. 3 x 3 의 one matrix를 생성한다
3. 2 x 2 의 zero matrix를 생성한다
4. 3 x 5의 rand 행렬을 생성한다


### 텐서 인덱스

In [ ]:
temp = torch.Tensor([0, 1, 2, 3, 4, 5, 6, 7])

print(temp[:]) # tensor element 전체
print(temp[1:4]) # index 1과 4 사이의 원소들 출력
print(temp[1:]) # index 1부터의 원소들 출력
print(temp[:4]) # index 4까지의 원소들 출력
print(temp[-1]) # 뒤에서 첫번째 원소 출력
print(temp[:-1]) # index -1 = 뒤에서부터 index 1에 해당하는 원소까지만 출력
print(temp[1:6:2]) # index 1과 6 사이의 원소 출력, 이때 2개 단위로 건너뛰면서

In [ ]:
temp2 = torch.Tensor([[1, 2, 3], [4, 5, 6]])

print(temp2)
print(temp2[1:])
print(temp2[1:, 1:])
print(temp2[1:, 0])

- 실습

1. 7 x 10 의 ones matrix를 생성한다
2. indexing을 활용해서 위에서 만든 matrix를 3 x 3 으로 바꾼다

### 텐서의 크기와 텐서 변환하기(reshape)

In [ ]:
# shape: Returns the size of the tensor
a = torch.Tensor([[1, 2, 3], [4, 5, 6]])

print(a)
print(a.shape)

In [ ]:
# size()
print(a.size())

In [ ]:
# Reshape: Returns a tensor with the same data and number of elements as the original tensor but with the specified shape. 
a_reshape = a.reshape(3, 2)
print(a_reshape)
print(a_reshape.shape)

a_reshape_2 = a.reshape(-1, 2) # the size -1 is inferred from other dimensions
print(a_reshape_2)
print(a_reshape_2.shape)

In [ ]:
# if shape is not compatible with the current shape:
a_no_reshape = a.reshape(4, 2)

In [ ]:
# View: Returns a new tensor with the same data as the original tensor but of a different shape.
# reshape과 거의 비슷하게 사용

x = torch.randn(4, 4)
print(x.size())

y = x.view(16)
print(y.size())

z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(z.size())

- 실습

1. 8x8 랜덤 행렬 생성한다
2. 크기를 바꿔주는 view를 사용하여 8x8를 64로 변환한다
3. -1을 사용하여 원래 크기 8x8 을 4x4x4로 변환한다

### 텐서 연산

In [ ]:
x = torch.ones(1, 2)
print(x)
y = torch.ones(5, 3)
print(y)

In [ ]:
print(x+y)

In [ ]:
y = torch.ones(5, 2)
print(y)

# 1.
print(x+y)
# 2. 
print(torch.add(x, y))
# 3.
result = torch.empty(5, 2)
torch.add(x, y, out=result)
print(result)
# 4. inplace
print(y.add_(x))

### 텐서를 numpy로 변환하기

In [ ]:
# tensor to numpy array

points = torch.ones(3, 4)
points_np = points.numpy()

print(points_np)

In [ ]:
# numpy arrray to tensor
points = torch.from_numpy(points_np)

print(points)

#### List, Numpy 배열을 텐서로 만들기

In [ ]:
import numpy as np

In [ ]:
l = [13,4] # 리스트 생성
r = np.array([4,56,7]) # 넘파이 배열 생성

In [ ]:
torch.tensor(l) # 리스트를 텐서로 쉽게 변환할 수 있다.

In [ ]:
torch.tensor(r) # 넘파이 배열을 텐서로 쉽게 변환할 수 있다.

## Backpropagation

- PyTorch는 역전파(backpropagation)를 위한 자동미분 제공

In [ ]:
# requires_grad=True는 해당 텐서(x)를 기준으로 모든 연산을 추적하는 옵션이다
# 즉, x에 대해서 미분가능
x = torch.ones(2,2, requires_grad=True)
print(x)

In [ ]:
# y는 x에 대한 식
y = x + 1

# z는 y에 대한 식
z = 2*y**2

# res는 z에 대한 식이다
res = z.mean()

# x에 대해 미분가능
print("y: ", y)
print("z: ", z)
print("Result: ", res)

In [ ]:
# res를 기준으로 역전파를 한다
# ex. loss.backward()

# res = (z_1 + .. +z_4)/4
# z_i = 2(y_i)**2
# z_i = 2(x_i+1)**2
# d(res)/dx_i = x_i + 1

res.backward()

In [ ]:
print(x)
print(x.grad)